#!/bin/sh

lib_failed=0
lib_passed=0
lib_failed_bad=0
lib_tests=0

echo '-- tests start --'
for f in `cat testlist`;
do
  let lib_tests=lib_tests+1 >/dev/null 2>&1
  ./$f >/dev/null 2>&1
  ret=$?
  case $ret in
    0)
      echo $f passed
      let lib_passed=lib_passed+1 >/dev/null 2>&1
      ;;
    1)
      echo $f failed
      let lib_failed=lib_failed+1 >/dev/null 2>&1
      ;;
    *)
      echo $f failed
      let lib_failed_bad=lib_failed_bad+1 >/dev/null 2>&1
      ;;
  esac
done
cat <<EOF
-- tests end --
tests      $lib_tests
passed     $lib_passed
failed     $lib_failed
crashed    $lib_failed_bad
EOF
